# Generated by Django 6.1.1 on 2026-09-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='account_number',
            field=models.CharField(blank=True, help_text='10 digit NUBAN', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='settlement_bank',
            field=models.CharField(blank=True, help_text='e.g. Access Bank', max_length=100, null=True),
        ),
    ]
